### ISSUE TITLE
Cannot Install on Windows 10

### ISSUE THREAD

**Issue by geauxtigers** [jalan/pdftotext#16]
I am running Win10 with the anaconda dist of python 3.6 and have the MS build tools and compiler installed.  I pip install the pdftotext package.  Installation begins and then terminates with this message:

```
pdftotext.cpp(3): fatal error C1083: Cannot open include file: 'poppler/cpp/poppler-document.h': No such file or directory
```

Any ideas?

**Comment by jalan** [comment]
You would need to get [poppler](https://poppler.freedesktop.org/) and its development files installed on Windows. I don't use Windows, so I am not much help, sorry.

If you figure something out, I will gladly add it to the README here!

**Comment by geauxtigers** [comment]
Thanks.  I am researching this but have not found any good guidance.  I will report back my findings.

**Comment by randiaz95** [comment]
Any updates on this problem? I happen to have this same thing.

**Comment by geauxtigers** [comment]
No, I didn’t. My solution ended up being in a completely different direction, using different packages.  This may be worth a mention in the README file for future Windows (10) users.

**Comment by rcy222** [comment]
All hope is not lost on the windows version.   There is a command line utility with the same name and you can use the subprocess package to execute pdftotext

PDFtotext windows download instruction, credit @s2t2
1. Go to https://www.xpdfreader.com/download.html and click "Download the Xpdf tools"
2. Uncompress/extract the zip file, and move the folder to a location like the Desktop or the Programs directory.
3. Inside the unzipped folder, copy the file bin64/pdftotext.exe into your project repository

**Comment by davidolmo** [comment]
> 3\. Inside the unzipped folder, copy the file bin64/pdftotext.exe into your project repository

You mean that it can be used from windows command prompt but not python?

**Comment by GuodongQi** [comment]
> > 3. Inside the unzipped folder, copy the file bin64/pdftotext.exe into your project repository
> 
> You mean that it can be used from windows command prompt but not python?

just copy files bin64/*.exe to your PYTHON PATH directory

**Comment by Mattwmaster58** [comment]
Any chance of prebuilt binaries being offered? Is it something that could be integrated into the CI setup?

**Comment by woodsjs** [comment]
I "ugly" installed pdftotext successfully on windows three times over the past two days, as the subprocess method is a non-starter for me. I have a writeup on SO 

[https://stackoverflow.com/questions/45912641/unable-to-install-pdftotext-on-python-3-6-missing-poppler/58139729#58139729 ](https://stackoverflow.com/questions/45912641/unable-to-install-pdftotext-on-python-3-6-missing-poppler/58139729#58139729 )

as well as on my blog, which has screenshots

[https://coder.haus/2019/09/27/installing-pdftotext-through-pip-on-windows-10/](https://coder.haus/2019/09/27/installing-pdftotext-through-pip-on-windows-10/ )

Please try this, let me know if it works. I'm hoping to take time to do it properly and potentially generate a PR.  

My solution requires Anaconda (for conda install).  First, install Microsoft VC++ build tools, download poppler for windows as well as conda install poppler, and copy some of the poppler files to different locations in the Anaconda directory structure.  Again, I have done this a total of 3 times and know it can be done better, but this will get you up and running.

**Comment by zacps** [comment]
I needed to apply this diff, then it worked for me:

```
diff --git a/setup.py b/setup.py
index 4c0e861..8a7337a 100644
--- a/setup.py
+++ b/setup.py
@@ -29,8 +29,8 @@ elif platform.system() in ["Windows"]:
         print("ERROR: CONDA_PREFIX is not found.")
         print("       Install Anaconda or fix missing CONDA_PREFIX and try again.")
         sys.exit(1)
-    anaconda_poppler_include_dir = path.join(conda_dir, "Library\include")
-    anaconda_poppler_library_dir = path.join(conda_dir, "Library\lib")
+    anaconda_poppler_include_dir = path.join(conda_dir, r"Library\include")
+    anaconda_poppler_library_dir = path.join(conda_dir, r"Library\lib")
     include_dirs = [anaconda_poppler_include_dir]
     library_dirs = [anaconda_poppler_library_dir]
 else:
```

**Comment by jalan** [comment]
@zacps I don't understand what your diff changes. Does it just change the strings into raw strings, or am I missing something? There are no escape characters, so aren't both versions equal?

```
$ python
>>> r"Library\include" == "Library\include"
True
```

**Comment by zacps** [comment]
`\i` is an invalid escape sequence, but now that I think about it I'm not sure why it changed anything.

**Comment by Kagigz** [comment]
Thank you so much @woodsjs for your blog post!

Just a quick update I would add:
When running `pip install` it's looking at the files inside my python3.6 libs folder and not the conda libs folder, so for me it worked when I copied the poppler-cpp.lib file into the `AppData/Local/Programs/Python/Python36/libs` folder.

**Comment by woodsjs** [comment]
Thanks for this, Katia! I've updated the post to point to the possibility of the file living in the Python/Python{PythonVersion}/libs directory.

**Comment by jalan** [comment]
@woodsjs I finally set up appveyor and pushed a release including your changes from #47: https://pypi.org/project/pdftotext/2.1.3/ . I hope it's nicer for Windows/conda users now. Thanks again!

**Comment by GadgetSteve** [comment]
@jalan It looks like you have yet to upload the Windows binaries to pypi so Windows users can get them!

**Comment by jalan** [comment]
@GadgetSteve ?

I didn't say I was planning to upload any Windows binaries

**Comment by GadgetSteve** [comment]
" I finally set up appveyor and pushed a release including your changes from #47: https://pypi.org/project/pdftotext/2.1.3/ . I hope it's nicer for Windows/conda users now." 

If you are not planning to upload any Windows binaries then the improvement for windows users is minimal - most do not have a compiler installed.

**Comment by palakjadwani** [comment]
I have had the hardest time installing pdftotext on my windows 10. Found @woodsjs page very useful as those were the exact errors I got. Finally I got it successfully installed but my PyCharm is not recognizing and giving :
ImportError: DLL load failed while importing pdftotext: The specified module could not be found.

I see inside site-packages that pip install doesn't download the jar file, maybe that is the problem. Please please someone help me out. Spent 2 days on this thing.

**Comment by GadgetSteve** [comment]
@palakjadwani this is the problem with there not being a binary download for the pdtotext package - you can find some workarounds at http://faculty.washington.edu/jwilker/559/2018/pdftotext.pdf but they are less than ideal.

**Comment by woodsjs** [comment]
@palakjadwani If you can see the package using the anaconda prompt (you can, correct?), this more than likely has NOTHING to do with the install of pdftotext. This is most likely because your pycharm install is not using the interpreter, conda, that you installed pdftotext under.

See Jetbrains documentation on changing your interpreter [https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html?_ga=2.75189201.2125986240.1606050657-56391306.1606050657#interpreter](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html?_ga=2.75189201.2125986240.1606050657-56391306.1606050657#interpreter)  You would add your existing anaconda environment.

I've tested this, as I do not use PyCharm, and was able to add my anaconda environment and get access to pdftotext.  I would also suggest shutting pycharm down and restarting to make the new interpreter active.

**Comment by GodMakesMe** [comment]
I have the wheel file of the pdftotext for cp38 version 3.8.5 64 bit.
Just go to power shell and do
cd [Location of the file] 
pip install ./[Wheel file [name]
Or
py -3.8 -m pip install ./[Wheel file name]

I am also attaching poppler files so you can extract these files in python destination folder.
[pdftotext.zip](https://github.com/jalan/pdftotext/files/5765091/pdftotext.zip)

**Comment by GodMakesMe** [comment]
> I have the wheel file of the pdftotext for cp38 version 3.8.5 64 bit.
> Just go to power shell and do
> cd [Location of the file]
> pip install ./[Wheel file [name]
> Or
> py -3.8 -m pip install ./[Wheel file name]
> 
> I am also attaching poppler files so you can extract these files in python destination folder.
> [pdftotext.zip](https://github.com/jalan/pdftotext/files/5765091/pdftotext.zip)

If any one have the wheel of pdftotext of version cp39 64 bit kindly share it.

**Comment by GodMakesMe** [comment]
Now I have the latest wheel file. version 39 64 Bit
[pdftotext.zip](https://github.com/jalan/pdftotext/files/5765373/pdftotext.zip)

**Comment by polyspastos** [comment]
hey! trying to install this i get the following error with 3.9:

```
(venv) (dir)>python -m pip install ./pdftotext-2.1.5-cp39-cp39-win_amd64.whl
Processing (dir)\pdftotext-2.1.5-cp39-cp39-win_amd64.whl
Installing collected packages: pdftotext
Successfully installed pdftotext-2.1.5

(venv) (dir)>python (script).py
Traceback (most recent call last):
  File "(dir)\(script).py", line 11, in <module>
    import pdftotext
ImportError: DLL load failed while importing pdftotext: The specified module could not be found.

(venv) (dir)>pip freeze
(misc modules)
pdftotext @ file:///C:/Users/tct/dev/konya.balazs/vub-pdf2xlsx-gui/pdftotext-2.1.5-cp39-cp39-win_amd64.whl
(misc modules)
```
Have you come across this already? Do you have any idea how to remedy the situation?
Thank you very much beforehand.

**Comment by polyspastos** [comment]
**Hey!**

I have come across the following while trying to install it:
```
(venv) (dir)>python -m pip install ./pdftotext-2.1.5-cp39-cp39-win_amd64.whl
Processing (dir)\pdftotext-2.1.5-cp39-cp39-win_amd64.whl
Installing collected packages: pdftotext
Successfully installed pdftotext-2.1.5

(venv) (dir)>python (script).py
Traceback (most recent call last):
  File "(dir)\(script).py", line 11, in <module>
    import pdftotext
ImportError: DLL load failed while importing pdftotext: The specified module could not be found.

(venv) (dir)>pip freeze
(misc modules)
pdftotext @ file:///(drive):/(dir)/pdftotext-2.1.5-cp39-cp39-win_amd64.whl
(misc modules)
```
Do you have any idea what could be causing this?

Any help would be greatly appreciated.

**Comment by GodMakesMe** [comment]
There is possibly the error in the environment.
Try to run it in anaconda Or install it in anaconda prompt.
If the problem persists then you can use PyPDF2 as the pdf extractor.
Else There could be issues in the installation of poppler.
I am also finding the solution.
You can also refer to the Coder Haus blog on this.
If you find the solution then please let me know.

**Comment by GadgetSteve** [comment]
I suspect that you need to have the poppler bin directory on your path for it to work. This is probably why the pdftotext.zip that had the wheel in also had poppler-0.68.0_x86 (1).7z in it. You will need to use 7-zip to extract this and add the_location_that_you_extract_to\bin to your path.

Hope that helps.

**Comment by GodMakesMe** [comment]
You can try latest version of poppler and extract the files according to the folders destination
And Then try installing pdftotext 
If you are using anaconda then you can run 
conda install -c conda-forge poppler

**Comment by ReMiOS** [comment]
I've had some trouble getting pdftotext working on Windows.
But i managed with the following steps:

download poppler: [https://anaconda.org/conda-forge/poppler/21.03.0/download/win-64/poppler-21.03.0-h9ff6ed8_0.tar.bz2](url)
copy the contents from ..\poppler-21.03.0-h9ff6ed8_0\Library\lib\ to ..\<Python-install-folder>\libs\
copy the contents from ..\poppler-21.03.0-h9ff6ed8_0\Library\include\poppler to ..\<Python-install-folder>\include\poppler
copy the DLLs from ..\poppler-21.03.0-h9ff6ed8_0\Library\include\bin\*.dll to ..\<Python-install-folder>\Lib\site-packages\

Copy the DLLs to c:\Python3\Lib\site-packages
charset.dll
freetype.dll
iconv.dll
libcrypto-1_1-x64.dll
libcurl.dll
liblzma.dll
libpng16.dll
libssh2.dll
openjp2.dll
tiff.dll
zlib.dll
zstd.dll

Now you can install pdftotext with:
# pip install pdftotext-2.1.6-cp39-cp39-win_amd64.whl

Files are in attachment
[PDFtoTEXT_Win10_x64.zip](https://github.com/jalan/pdftotext/files/6938715/PDFtoTEXT_Win10_x64.zip)
