### ISSUE TITLE
macOS: `setup.py` fails when `brew` is not in PATH

### ISSUE THREAD

**Issue by smancill** [jalan/pdftotext#95]
`setup.py` fails when `brew` is not in PATH (from nixpkgs darwin build: https://hydra.nixos.org/build/157649245/nixlog/4)

```
Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.9-pdftotext-2.2.1.drv-0/pdftotext-2.2.1/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 66, in <module>
    brew_include, brew_library = brew_poppler_include()
  File "setup.py", line 25, in brew_poppler_include
    brew_list = subprocess.check_output(["brew", "list", "poppler"])
  File "/nix/store/x0fw0l4d6zwgfdwbpp23iwhm3c6a1hh3-python3-3.9.6/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/x0fw0l4d6zwgfdwbpp23iwhm3c6a1hh3-python3-3.9.6/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/x0fw0l4d6zwgfdwbpp23iwhm3c6a1hh3-python3-3.9.6/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/x0fw0l4d6zwgfdwbpp23iwhm3c6a1hh3-python3-3.9.6/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'brew'
```

**Comment by jalan** [comment]
Fixed in version 2.2.2. Thanks!
